version: '3'
services:
  app:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8081:8081"
    volumes:
      - .:/app
#       - /usr/src/app/node_modules